# 应用模块配置
[web]
    # web 服务绑定地址
    binding = "192.168.124.18"
    # web 服务端口
    port = 4455
    # static 静态文件路径
    static = "D:\\project\\go\\src\\github.com\\lack-io\\cirrus\\static"

# storage模块配置
[storage]
    # storage url 存储方式，默认为 redis
    kind = "redis"

    [storage.redis]
        # redis 地址
        addr = "192.168.10.10:6379"
        # redis 用户名
        username = ""
        # redis 密码
        password = ""
        # redis 连接数
        pools = 5

# store 配置
[store]
    # 使用的数据库类型
    # 默认使用 sqlite
    db = "sqlite"

    # sqlite 配置参数
    [store.sqlite]
        name = "cirrus.db"

# 爬虫客户端配置
[client]
    # 是否显示 chrome
    headless = true
    # 是否加载图片
    skip_image = true
    # 并发连接数
    connections = 5

# 代理模块配置
[proxy]
    # 是否使用代理爬取内容
    enable = true
    # 代理商名称, 支持的代理商业
    #   - 极光爬虫代理：http://h.jiguangdaili.com/
    # 默认为极光代理 jg
    agent = "jg"

    # 代理池中的代理个数
    size = 5

    [proxy.jg]
        # 用户ID
        neek = "29394"
        # 代理接口的 appkey
        api_appkey = "ec28da82d45f195e3d962c86dce693f4"
        # 余额查询接口的 appkey
        balance_appkey = "ec36c20228d8a97ff5dc56273dda535d"

#[logger]
#    # 日志文件的位置
#    filename = "access.log"
#    # 每个日志文件的大小(单位为MB)
#    maxsize = 100
#    # 保留旧文件的最大个数
#    maxbackups = 10
#    # 保留旧文件的最大天数
#    maxages = 7
#    # 是否使用本地时间
#    localtime = true
#    # 是否压缩/归档旧文件
#    compress = false